### ISSUE TITLE
Ability to correct snippet range

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/logdetective-website#156]
I can review the text of the snippet, but the range of the snippet in the log cannot be altered (and sometimes they are not visible too).

**Comment by FrostyX** [comment]
> and sometimes they are not visible too

This will be fixed by #152

> but the range of the snippet in the log cannot be altered

Though doable, I cannot think of a UI that would be easy to understand and easy to implement, so I am afraid this will be a WONTFIX with a documentation workaround (downvote the wrong snippet, create a new one correctly).

Or do you have some design in mind?

**Comment by TomasTomecek** [comment]
> > and sometimes they are not visible too
> 
> This will be fixed by #152

I just went through a few reviews and I can still reach snippets that are not visible in the log. I will look into this more.

**Comment by FrostyX** [comment]
> downvote the wrong snippet, create a new one correctly

This will work if the snippet is in an entirely different place but it won't work if you want to make an existing selection smaller or larger because we don't allow creating snippets over other snippets because it would be too hard to implement (I can explain the problems it causes on a meeting or here if you want to)
